import type { components } from "./schema";

export type AlertOut = components["schemas"]["AlertOut"];
export type AlertOutWithQc = AlertOut & {
  qc_record_id?: number | null;
  qc_record_timestamp?: string | null;
};
export type AlertStatus = components["schemas"]["AlertStatus"];
export type AlertUpdate = components["schemas"]["AlertUpdate"];
export type AnalyteIn = components["schemas"]["AnalyteIn"];
export type AnalyteOut = components["schemas"]["AnalyteOut"];
export type AnalyteUpdate = components["schemas"]["AnalyteUpdate"];
export type AuditEntryOut = components["schemas"]["AuditEntryOut"];
export type BayesianRisk = components["schemas"]["BayesianRisk"];
export type CapaIn = components["schemas"]["CapaIn"];
export type CapaOut = components["schemas"]["CapaOut"];
export type CapaStatus = components["schemas"]["CapaStatus"];
export type CsvIngestResult = components["schemas"]["CsvIngestResult"];
export type ControlMaterialOut = components["schemas"]["ControlMaterialOut"];
export type CurrentUserOut = components["schemas"]["CurrentUserOut"];
export type Disposition = components["schemas"]["Disposition"];
export type EntrySource = components["schemas"]["EntrySource"];
export type EventType = components["schemas"]["EventType"];
export type FrequentistSignal = components["schemas"]["FrequentistSignal"];
export type IngestionResult = components["schemas"]["IngestionResult"];
export type CollectorAction = components["schemas"]["CollectorAction"];
export type CollectorTransferEventIn = components["schemas"]["CollectorTransferEventIn"];
export type CollectorTransferEventOut = components["schemas"]["CollectorTransferEventOut"];
export type ImportArtifactOut = components["schemas"]["ImportArtifactOut"];
export type ImportBatchDetailOut = components["schemas"]["ImportBatchDetailOut"];
export type ImportBatchOut = components["schemas"]["ImportBatchOut"];
export type ImportBatchStatus = components["schemas"]["ImportBatchStatus"];
export type ImportCreateOut = components["schemas"]["ImportCreateOut"];
export type ImportRowOut = components["schemas"]["ImportRowOut"];
export type ImportRowStatus = components["schemas"]["ImportRowStatus"];
export type ImportRowType = components["schemas"]["ImportRowType"];
export type ImportRowUpdate = components["schemas"]["ImportRowUpdate"];
export type InstrumentPeakOut = components["schemas"]["InstrumentPeakOut"];
export type InstrumentRunOut = components["schemas"]["InstrumentRunOut"];
export type InvestigationIn = components["schemas"]["InvestigationIn"];
export type InvestigationOut = components["schemas"]["InvestigationOut"];
export type InvestigationStatus = components["schemas"]["InvestigationStatus"];
export type InstrumentIn = components["schemas"]["InstrumentIn"];
export type InstrumentOut = components["schemas"]["InstrumentOut"];
export type InstrumentUpdate = components["schemas"]["InstrumentUpdate"];
export type KioskLayoutOut = components["schemas"]["KioskLayoutOut"];
export type KioskPanelOut = components["schemas"]["KioskPanelOut"];
export type LotSegmentOut = components["schemas"]["LotSegmentOut"];
export type MethodIn = components["schemas"]["MethodIn"];
export type MethodOut = components["schemas"]["MethodOut"];
export type MethodUpdate = components["schemas"]["MethodUpdate"];
export type QCEventIn = components["schemas"]["QCEventIn"];
export type QCEventOut = components["schemas"]["QCEventOut"];
export type QCBacklogItemIn = components["schemas"]["QCBacklogItemIn"];
export type QCBacklogItemOut = components["schemas"]["QCBacklogItemOut"];
export type QCBacklogItemUpdate = components["schemas"]["QCBacklogItemUpdate"];
export type QCBacklogPriority = components["schemas"]["QCBacklogPriority"];
export type QCBacklogSource = components["schemas"]["QCBacklogSource"];
export type QCBacklogStatus = components["schemas"]["QCBacklogStatus"];
export type QCCommentIn = components["schemas"]["QCCommentIn"];
export type QCCommentOut = components["schemas"]["QCCommentOut"];
export type QCCommentTargetType = components["schemas"]["QCCommentTargetType"];
export type QCRecordChartOut = components["schemas"]["QCRecordChartOut"];
export type QCRecordChartOutEvaluated = QCRecordChartOut & {
  signals?: FrequentistSignal[] | null;
  bayesian_risk?: BayesianRisk | null;
  disposition?: Disposition | null;
};
export type QCRecordIn = components["schemas"]["QCRecordIn"];
export type QCRecordQuarantineOut = components["schemas"]["QCRecordQuarantineOut"];
export type QCRecordResolutionIn = components["schemas"]["QCRecordResolutionIn"];
export type Permission = components["schemas"]["Permission"];
export type ParserProfileIn = components["schemas"]["ParserProfileIn"];
export type ParserProfileOut = components["schemas"]["ParserProfileOut"];
export type ParserProfileStatus = components["schemas"]["ParserProfileStatus"];
export type ParserProfileType = components["schemas"]["ParserProfileType"];
export type ParserProfileUpdate = components["schemas"]["ParserProfileUpdate"];
export type QuarantineReason = components["schemas"]["QuarantineReason"];
export type QuarantineResult = components["schemas"]["QuarantineResult"];
export type QuarantineReviewIn = components["schemas"]["QuarantineReviewIn"];
export type QuarantineStatus = components["schemas"]["QuarantineStatus"];
export type ReportSummaryOut = components["schemas"]["ReportSummaryOut"];
export type Role = components["schemas"]["Role"];
export type SignalSeverity = components["schemas"]["SignalSeverity"];
export type StreamChartOut = components["schemas"]["StreamChartOut"];
export type StreamChartOutEvaluated = StreamChartOut & {
  records: QCRecordChartOutEvaluated[];
  alerts: AlertOutWithQc[];
};
export type StreamConfigIn = components["schemas"]["StreamConfigIn"];
export type StreamConfigOut = components["schemas"]["StreamConfigOut"];
export type StreamSetupApplyOut = components["schemas"]["StreamSetupApplyOut"];
export type StreamSetupBatchIn = components["schemas"]["StreamSetupBatchIn"];
export type StreamSetupIn = components["schemas"]["StreamSetupIn"];
export type StreamSetupPreviewOut = components["schemas"]["StreamSetupPreviewOut"];
export type StreamSetupPreviewRow = components["schemas"]["StreamSetupPreviewRow"];
