/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Alert Status */
        patch: operations["update_alert_status_alerts__alert_id__patch"];
        trace?: never;
    };
    "/analytes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analytes */
        get: operations["list_analytes_analytes_get"];
        put?: never;
        /** Create Analyte */
        post: operations["create_analyte_analytes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytes/{analyte_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Analyte */
        patch: operations["update_analyte_analytes__analyte_id__patch"];
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Capas */
        get: operations["list_capas_capas_get"];
        put?: never;
        /** Create Capa Record */
        post: operations["create_capa_record_capas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capas/{capa_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Capa Record */
        patch: operations["update_capa_record_capas__capa_id__patch"];
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_instruments_get"];
        put?: never;
        /** Create Instrument */
        post: operations["create_instrument_instruments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Instrument */
        patch: operations["update_instrument_instruments__instrument_id__patch"];
        trace?: never;
    };
    "/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_investigations_get"];
        put?: never;
        /** Create Investigation Record */
        post: operations["create_investigation_record_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Investigation Record */
        patch: operations["update_investigation_record_investigations__investigation_id__patch"];
        trace?: never;
    };
    "/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Methods */
        get: operations["list_methods_methods_get"];
        put?: never;
        /** Create Method */
        post: operations["create_method_methods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/methods/{method_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Method */
        patch: operations["update_method_methods__method_id__patch"];
        trace?: never;
    };
    "/qc/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_qc_events_get"];
        put?: never;
        /** Ingest Event */
        post: operations["ingest_event_qc_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qc/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Qc Record */
        post: operations["ingest_qc_record_qc_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qc/records/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Qc Records Csv */
        post: operations["ingest_qc_records_csv_qc_records_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qc/records/{record_id}/resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Resolve Qc Record */
        patch: operations["resolve_qc_record_qc_records__record_id__resolution_patch"];
        trace?: never;
    };
    "/reports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Summary */
        get: operations["report_summary_reports_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streams */
        get: operations["list_streams_streams_get"];
        put?: never;
        /** Create Stream */
        post: operations["create_stream_streams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/{stream_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Chart */
        get: operations["stream_chart_streams__stream_id__chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/{stream_id}/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stream Versions */
        get: operations["list_stream_versions_streams__stream_id__configs_get"];
        put?: never;
        /** Create Stream Version */
        post: operations["create_stream_version_streams__stream_id__configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/{stream_id}/priors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Priors */
        get: operations["list_priors_streams__stream_id__priors_get"];
        put?: never;
        /** Create Prior */
        post: operations["create_prior_streams__stream_id__priors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /**
             * Acknowledged
             * @default false
             */
            acknowledged: boolean;
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** Acknowledged By */
            acknowledged_by?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            bayesian_risk: components["schemas"]["BayesianRisk"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            disposition: components["schemas"]["Disposition"];
            /** Due At */
            due_at?: string | null;
            /** Id */
            id: string;
            /** Signals */
            signals: components["schemas"]["FrequentistSignal"][];
            status?: components["schemas"]["AlertStatus"] | null;
            /** Stream Id */
            stream_id: string;
        };
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "open" | "acknowledged" | "closed";
        /** AlertSummary */
        AlertSummary: {
            /** Acknowledged */
            acknowledged: number;
            /** Open */
            open: number;
            /** Total */
            total: number;
        };
        /** AlertUpdate */
        AlertUpdate: {
            /** Acknowledged By */
            acknowledged_by?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Due At */
            due_at?: string | null;
            status?: components["schemas"]["AlertStatus"] | null;
        };
        /** AnalyteIn */
        AnalyteIn: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Method Id */
            method_id: number;
            /** Name */
            name: string;
            /** Units */
            units?: string | null;
        };
        /** AnalyteOut */
        AnalyteOut: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: number;
            /** Method Id */
            method_id: number;
            /** Name */
            name: string;
            /** Units */
            units?: string | null;
        };
        /** AnalyteUpdate */
        AnalyteUpdate: {
            /** Active */
            active?: boolean | null;
            /** Method Id */
            method_id?: number | null;
            /** Name */
            name?: string | null;
            /** Units */
            units?: string | null;
        };
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /** After */
            after: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Before */
            before: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Entity Type */
            entity_type: string;
            /** Reason */
            reason: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** BayesianRisk */
        BayesianRisk: {
            /** Credible Interval */
            credible_interval?: [
                number,
                number
            ] | null;
            /** Posterior Mean */
            posterior_mean?: number | null;
            /** Posterior Sigma */
            posterior_sigma?: number | null;
            /** Predictive Sigma */
            predictive_sigma?: number | null;
            /** Probability Outside Limits */
            probability_outside_limits: number;
            /** Risk Score */
            risk_score: number;
        };
        /** Body_ingest_qc_records_csv_qc_records_csv_post */
        Body_ingest_qc_records_csv_qc_records_csv_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CapaIn */
        CapaIn: {
            /** Alert Id */
            alert_id?: string | null;
            /** Corrective Actions */
            corrective_actions?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /** Due At */
            due_at?: string | null;
            /** Effectiveness Criteria */
            effectiveness_criteria?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Investigation Id */
            investigation_id?: number | null;
            /** Owners */
            owners?: string[] | null;
            /** Preventive Actions */
            preventive_actions?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /** Root Cause Category */
            root_cause_category?: string | null;
            status?: components["schemas"]["CapaStatus"] | null;
            /** Verification Plan */
            verification_plan?: string | null;
        };
        /** CapaOut */
        CapaOut: {
            /** Alert Id */
            alert_id?: string | null;
            /** Corrective Actions */
            corrective_actions?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Due At */
            due_at?: string | null;
            /** Effectiveness Criteria */
            effectiveness_criteria?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Id */
            id: number;
            /** Investigation Id */
            investigation_id?: number | null;
            /** Owners */
            owners?: string[] | null;
            /** Preventive Actions */
            preventive_actions?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /** Root Cause Category */
            root_cause_category?: string | null;
            status: components["schemas"]["CapaStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Verification Plan */
            verification_plan?: string | null;
        };
        /**
         * CapaStatus
         * @enum {string}
         */
        CapaStatus: "draft" | "open" | "implementing" | "effectiveness_check" | "closed" | "reopened";
        /** CapaSummary */
        CapaSummary: {
            /** Open */
            open: number;
            /** Total */
            total: number;
        };
        /** CsvIngestResult */
        CsvIngestResult: {
            /** Accepted */
            accepted: number;
            /** Errors */
            errors: components["schemas"]["CsvRowError"][];
            /** Results */
            results: components["schemas"]["IngestionResult"][];
        };
        /** CsvRowError */
        CsvRowError: {
            /** Error */
            error: string;
            /** Row */
            row: number;
        };
        /**
         * Disposition
         * @enum {string}
         */
        Disposition: "accept" | "monitor" | "hold-for-review" | "reject";
        /**
         * DuplicateStatus
         * @enum {string}
         */
        DuplicateStatus: "unique" | "duplicate" | "possible_duplicate";
        /**
         * EntrySource
         * @enum {string}
         */
        EntrySource: "automated" | "manual";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "calibration" | "maintenance" | "reagent_lot_change" | "control_material_lot_change" | "software_update" | "environmental_alert";
        /** FrequentistSignal */
        FrequentistSignal: {
            /** Evidence */
            evidence: string;
            /** Rule */
            rule: string;
            severity: components["schemas"]["SignalSeverity"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionResult */
        IngestionResult: {
            alert_created: components["schemas"]["AlertOut"] | null;
            audit_entry: components["schemas"]["AuditEntryOut"];
            duplicate: components["schemas"]["DuplicateStatus"];
            /** Idempotency Key */
            idempotency_key?: string | null;
            qc: components["schemas"]["QCRecordOut"];
            /** Status */
            status: string;
        };
        /** InstrumentIn */
        InstrumentIn: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model */
            model?: string | null;
            /** Name */
            name: string;
            /** Site */
            site?: string | null;
        };
        /** InstrumentOut */
        InstrumentOut: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: number;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model */
            model?: string | null;
            /** Name */
            name: string;
            /** Site */
            site?: string | null;
        };
        /** InstrumentUpdate */
        InstrumentUpdate: {
            /** Active */
            active?: boolean | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model */
            model?: string | null;
            /** Name */
            name?: string | null;
            /** Site */
            site?: string | null;
        };
        /** InvestigationIn */
        InvestigationIn: {
            /** Alert Id */
            alert_id?: string | null;
            /** Containment */
            containment?: string | null;
            /** Data Reviewed */
            data_reviewed?: string | null;
            /** Decision */
            decision?: string | null;
            /** Outcome */
            outcome?: string | null;
            /** Problem Statement */
            problem_statement: string;
            status?: components["schemas"]["InvestigationStatus"] | null;
            /** Suspected Cause */
            suspected_cause?: string | null;
        };
        /** InvestigationOut */
        InvestigationOut: {
            /** Alert Id */
            alert_id?: string | null;
            /** Containment */
            containment?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Data Reviewed */
            data_reviewed?: string | null;
            /** Decision */
            decision?: string | null;
            /** Id */
            id: number;
            /** Outcome */
            outcome?: string | null;
            /** Problem Statement */
            problem_statement: string;
            status: components["schemas"]["InvestigationStatus"];
            /** Suspected Cause */
            suspected_cause?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InvestigationStatus
         * @enum {string}
         */
        InvestigationStatus: "open" | "in_review" | "closed";
        /** InvestigationSummary */
        InvestigationSummary: {
            /** Open */
            open: number;
            /** Total */
            total: number;
        };
        JsonValue: unknown;
        /** LotSegmentOut */
        LotSegmentOut: {
            /** Control Material Lot */
            control_material_lot: string;
            /** Count */
            count: number;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** MethodIn */
        MethodIn: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Instrument Id */
            instrument_id: number;
            /** Name */
            name: string;
            /** Technique */
            technique?: string | null;
        };
        /** MethodOut */
        MethodOut: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: number;
            /** Instrument Id */
            instrument_id: number;
            /** Name */
            name: string;
            /** Technique */
            technique?: string | null;
        };
        /** MethodUpdate */
        MethodUpdate: {
            /** Active */
            active?: boolean | null;
            /** Instrument Id */
            instrument_id?: number | null;
            /** Name */
            name?: string | null;
            /** Technique */
            technique?: string | null;
        };
        /** PriorConfigIn */
        PriorConfigIn: {
            /** Alpha0 */
            alpha0: number;
            /** Beta0 */
            beta0: number;
            /** Effective From */
            effective_from?: string | null;
            /** Kappa0 */
            kappa0: number;
            /** Mu0 */
            mu0: number;
            /** Stream Id */
            stream_id: string;
        };
        /** PriorConfigOut */
        PriorConfigOut: {
            /** Alpha0 */
            alpha0: number;
            /** Beta0 */
            beta0: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Kappa0 */
            kappa0: number;
            /** Mu0 */
            mu0: number;
            /** Stream Id */
            stream_id: string;
            /** Version */
            version: number;
        };
        /** QCEventIn */
        QCEventIn: {
            /** Analyte */
            analyte?: string | null;
            event_type: components["schemas"]["EventType"];
            /** Instrument Id */
            instrument_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Method Id */
            method_id?: string | null;
            /** Stream Id */
            stream_id?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** QCEventOut */
        QCEventOut: {
            /** Analyte */
            analyte?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            event_type: components["schemas"]["EventType"];
            /** Id */
            id: number;
            /** Instrument Id */
            instrument_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Method Id */
            method_id?: string | null;
            /** Stream Id */
            stream_id?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** QCRecordChartOut */
        QCRecordChartOut: {
            /** Control Material Lot */
            control_material_lot: string;
            /** Id */
            id: number;
            /** Include In Stats */
            include_in_stats: boolean;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolved Reason */
            resolved_reason?: string | null;
            /** Result Value */
            result_value: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** QCRecordIn */
        QCRecordIn: {
            /** Analyte */
            analyte: string;
            /** Calibration Status */
            calibration_status: string | null;
            /** Comments */
            comments: string | null;
            /** Control Material Lot */
            control_material_lot: string;
            /** @default automated */
            entry_source: components["schemas"]["EntrySource"];
            /** Flags */
            flags?: string[] | null;
            /** Instrument Id */
            instrument_id: string;
            /** Method Id */
            method_id: string;
            /** Operator Id */
            operator_id: string | null;
            /** Qc Level */
            qc_level: string;
            /** Reagent Lot */
            reagent_lot: string | null;
            /** Result Value */
            result_value: number;
            /** Run Id */
            run_id: string | null;
            /** Stream Id */
            stream_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Units */
            units: string;
        };
        /** QCRecordOut */
        QCRecordOut: {
            bayesian_risk: components["schemas"]["BayesianRisk"];
            disposition: components["schemas"]["Disposition"];
            record: components["schemas"]["QCRecordIn"];
            /** Signals */
            signals: components["schemas"]["FrequentistSignal"][];
        };
        /** QCRecordResolutionIn */
        QCRecordResolutionIn: {
            /** Include In Stats */
            include_in_stats: boolean;
            /** Resolved Reason */
            resolved_reason?: string | null;
        };
        /** QCRecordResolutionOut */
        QCRecordResolutionOut: {
            /** Id */
            id: number;
            /** Include In Stats */
            include_in_stats: boolean;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolved By */
            resolved_by?: string | null;
            /** Resolved Reason */
            resolved_reason?: string | null;
            /** Result Value */
            result_value: number;
            /** Stream Id */
            stream_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ReportSummaryOut */
        ReportSummaryOut: {
            alerts: components["schemas"]["AlertSummary"];
            capas: components["schemas"]["CapaSummary"];
            investigations: components["schemas"]["InvestigationSummary"];
        };
        /**
         * SignalSeverity
         * @enum {string}
         */
        SignalSeverity: "action" | "warn";
        /** StreamChartOut */
        StreamChartOut: {
            /** Alerts */
            alerts: components["schemas"]["AlertOut"][];
            /** Events */
            events: components["schemas"]["QCEventOut"][];
            /** Lot Segments */
            lot_segments: components["schemas"]["LotSegmentOut"][];
            /** Records */
            records: components["schemas"]["QCRecordChartOut"][];
        };
        /** StreamConfigIn */
        StreamConfigIn: {
            /**
             * Action Limit Sd
             * @default 3
             */
            action_limit_sd: number;
            /** Allowed Units */
            allowed_units?: string[] | null;
            /** Analyte */
            analyte: string;
            /** Baseline End */
            baseline_end?: string | null;
            /** Baseline Start */
            baseline_start?: string | null;
            /** Control Material Lot */
            control_material_lot: string;
            /** Effective From */
            effective_from?: string | null;
            /** Instrument */
            instrument: string;
            /** Matrix */
            matrix?: string | null;
            /** Max Value */
            max_value?: number | null;
            /** Method */
            method: string;
            /** Min Value */
            min_value?: number | null;
            /** Qc Level */
            qc_level: string;
            /**
             * Risk Threshold Hold
             * @default 80
             */
            risk_threshold_hold: number;
            /**
             * Risk Threshold Warn
             * @default 50
             */
            risk_threshold_warn: number;
            /** Rule Set */
            rule_set?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Sigma */
            sigma: number;
            /** Site */
            site?: string | null;
            /** Stream Id */
            stream_id: string;
            /** Target Value */
            target_value: number;
            /** Unit Conversions */
            unit_conversions?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Units */
            units: string;
            /**
             * Warning Limit Sd
             * @default 2
             */
            warning_limit_sd: number;
        };
        /** StreamConfigOut */
        StreamConfigOut: {
            /**
             * Action Limit Sd
             * @default 3
             */
            action_limit_sd: number;
            /** Allowed Units */
            allowed_units?: string[] | null;
            /** Analyte */
            analyte: string;
            /** Baseline End */
            baseline_end?: string | null;
            /** Baseline Start */
            baseline_start?: string | null;
            /** Control Material Lot */
            control_material_lot: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Instrument */
            instrument: string;
            /** Matrix */
            matrix?: string | null;
            /** Max Value */
            max_value?: number | null;
            /** Method */
            method: string;
            /** Min Value */
            min_value?: number | null;
            /** Qc Level */
            qc_level: string;
            /**
             * Risk Threshold Hold
             * @default 80
             */
            risk_threshold_hold: number;
            /**
             * Risk Threshold Warn
             * @default 50
             */
            risk_threshold_warn: number;
            /** Rule Set */
            rule_set?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Sigma */
            sigma: number;
            /** Site */
            site?: string | null;
            /** Stream Id */
            stream_id: string;
            /** Target Value */
            target_value: number;
            /** Unit Conversions */
            unit_conversions?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Units */
            units: string;
            /** Version */
            version: number;
            /**
             * Warning Limit Sd
             * @default 2
             */
            warning_limit_sd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alerts_alerts_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_status_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analytes_analytes_get: {
        parameters: {
            query?: {
                method_id?: number | null;
                active?: boolean | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analyte_analytes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_analyte_analytes__analyte_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                analyte_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_audit_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_capas_capas_get: {
        parameters: {
            query?: {
                status_filter?: components["schemas"]["CapaStatus"] | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_capa_record_capas_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_capa_record_capas__capa_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                capa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instruments_instruments_get: {
        parameters: {
            query?: {
                active?: boolean | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_instrument_instruments_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_instrument_instruments__instrument_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_investigations_get: {
        parameters: {
            query?: {
                status_filter?: components["schemas"]["InvestigationStatus"] | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_record_investigations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investigation_record_investigations__investigation_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                investigation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_methods_methods_get: {
        parameters: {
            query?: {
                instrument_id?: number | null;
                active?: boolean | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_method_methods_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MethodIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_method_methods__method_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                method_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MethodUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_qc_events_get: {
        parameters: {
            query?: {
                stream_id?: string | null;
                event_type?: components["schemas"]["EventType"] | null;
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QCEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_event_qc_events_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QCEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QCEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_qc_record_qc_records_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QCRecordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_qc_records_csv_qc_records_csv_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_qc_records_csv_qc_records_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvIngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_qc_record_qc_records__record_id__resolution_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QCRecordResolutionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QCRecordResolutionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_summary_reports_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_streams_streams_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stream_streams_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chart_streams__stream_id__chart_get: {
        parameters: {
            query?: {
                limit?: number;
                start?: string | null;
                end?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stream_versions_streams__stream_id__configs_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stream_version_streams__stream_id__configs_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_priors_streams__stream_id__priors_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_prior_streams__stream_id__priors_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriorConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
